[build-system]
requires = [
    "setuptools>=42",
    "torch",
    "tqdm>=4.62.3",
    "simpletransformers==0.63.6",
    "transformers==4.14.1",
    "spacy==3.1.3",
]
build-backend = "setuptools.build_meta"